# Generated by Django 5.0.4 on 2024-06-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_reabastecimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='reabastecimiento',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado')], default='pendiente', max_length=10),
        ),
    ]
