# Generated by Django 5.0.4 on 2024-06-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_venta'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
